apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mapping-service
spec:
  {{- if .Values.global }}
  ingressClassName: {{ .Values.global.ingress.ingressClassName | quote }}
  {{- else }}
  ingressClassName: "nginx"
  {{- end }}
  rules:
  {{- if .Values.global }}
  - host: {{ .Values.global.ingress.host | quote }}
  {{- else }}
  - host: {{ .Values.ingress.host | quote }}
  {{- end }}
  http:
    paths:
      - path: /rest/Spatial/WMS
        pathType: Prefix
        backend:
          service:
            name: mapping-service
            port:
              number: 8080
      - path: /rest/Spatial/MappingService
        pathType: Prefix
        backend:
          service:
            name: mapping-service
            port:
              number: 8080
      - path: /soap/MappingService
        pathType: Prefix
        backend:
          service:
            name: mapping-service
            port:
              number: 8080