image:
  tag: 7.0
credentials:
  # SECURITY WARNING: Do NOT use default credentials in production!
  # Set these values using --set flags or a secure values file during deployment
  # Example: helm install --set credentials.rootUsername=<user> --set credentials.rootPassword=<secure-password>
  # Or use Kubernetes Secrets: kubectl create secret generic mongo-credentials --from-literal=username=<user> --from-literal=password=<secure-password>
  rootUsername: ""
  rootPassword: ""
resources:
  requestCPU: 500m
  requestMemory: 512Mi
  limitCPU: 2000m
  limitMemory: 2Gi